# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# FIXME: SSH or tooling that requires libnss-cache (https://github.com/google/libnss-cache)
# seems to fail since the library is not present. When I have a better understanding of Nix
# let's fix this.
# Looks like they either fixed this and moved to a GRTE version of libnss
# [[ ! -f /lib/x86_64-linux-gnu/libnss_cache.so.2 ]] || export LD_PRELOAD=/lib/x86_64-linux-gnu/libnss_cache.so.2:$LD_PRELOAD

# Got this sweet function from HackerNews
function frg {
    result=$(rg --ignore-case --color=always --line-number --no-heading "$@" |
      fzf --ansi \
          --color 'hl:-1:underline,hl+:-1:underline:reverse' \
          --delimiter ':' \
          --preview "bat --color=always {1} --theme='Solarized (light)' --highlight-line {2}" \
          --preview-window 'up,60%,border-bottom,+{2}+3/3,~3')
    file=${result%%:*}
    linenumber=$(echo "${result}" | cut -d: -f2)
    if [[ -n "$file" ]]; then
            $EDITOR +"${linenumber}" "$file"
    fi
  }

# go/hi-guide
# TODO(fmzakari): only include this on google machines
source /etc/bash.bashrc.d/shell_history_forwarder.sh
if [[ -f /etc/bash_completion.d/g4d ]]; then
  source /etc/bash_completion.d/p4
  source /etc/bash_completion.d/g4d
fi
if [[ -f /etc/bash_completion.d/hgd ]]; then
  source /etc/bash_completion.d/hgd
fi
if [[ -f /etc/bash_completion.d/blaze ]]; then
  source /etc/bash_completion.d/blaze
fi
if [[ -f /etc/bash_completion.d/bazel ]]; then
  source /etc/bash_completion.d/bazel
fi