name: "Build & Test (nix)"

# FIXME: This build is too large and runs out of space
# on github runners.
# on:
#   pull_request:
#   push:
#     branches:
#       - master
on: workflow_dispatch

jobs:
  build:
    runs-on: [self-hosted, x86_64-linux]
    strategy:
      matrix:
        machine: [nyx, nixie, altaria]
    steps:
    - uses: actions/checkout@v4
    # I don't think we need the cache as we are building on our
    # self-hosted runner which has access to /nix/store; 
    # only a single machine.
    #
    # - name: Run the Magic Nix Cache
    #  uses: DeterminateSystems/magic-nix-cache-action@main
    #
    # This seems to cause memory exhaustion and causes the EC2 instance
    # to crash.
    #
    # - name: Check
    #  run: |
    #    nix flake check
    - name: Build
      run: |
        nix build .#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel -L