name: "Build & Test (nix)"

# FIXME: This build is too large and runs out of space
# on github runners.
# on:
#   pull_request:
#   push:
#     branches:
#       - master
on: workflow_dispatch

jobs:
  build:
    runs-on: [self-hosted, x86_64]
    steps:
    - uses: actions/checkout@v4
    # I don't think we need the cache as we are building on our
    # self-hosted runner which has access to /nix/store; 
    # only a single machine.
    #
    # - name: Run the Magic Nix Cache
    #  uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Check
      run: |
        nix flake check
        
        nix build .#nixosConfigurations.nyx.config.system.build.toplevel
        nix build .#nixosConfigurations.nixie.config.system.build.toplevel
        nix build .#nixosConfigurations.altaria.config.system.build.toplevel